### ISSUE TITLE
modernizr.js not found

### ISSUE THREAD

**Issue by intelligence** [roots/roots-rewrites#10]
I've added this plugin to my bedrock install. Pretty straight forward, also changed the rewriting rules as mentioned in #9.

My rewriting rules now look like this

    location ~ ^/assets/(img|js|css|fonts)/(.*)$ {
      try_files $uri $uri/ /app/themes/<theme name>/assets/$1/$2;
    }
    location ~ ^/plugins/(.*)$ {
      try_files $uri $uri/ /wp-content/plugins/$1?$query_string;
    }

I guess something still is off with the rules as it can't find modernizr.js

    http://domain.dev/assets/vendor/modernizr/modernizr.js 404 (Not Found)

**Comment by retlehs** [comment]
This plugin isn't supported, and definitely don't recommend using it with Bedrock

**Comment by retlehs** [comment]
anyway, the problem is you're trying to use `assets/vendor/` which isn't getting rewritten. as you can see from the rules you pasted, the only supported folders within `assets/` from the root are: `img/`, `js/`, `css/`, `fonts/`. update your nginx rules to get it working, or better yet, don't do this at all :wink:

**Comment by intelligence** [comment]
Hehe, yeah, I understand that you don't promote this together with Bedrock. Bit curious as to why though?

I noticed that roots.io seems to be running with similar rewrite rules as this plugin applies. No?

**Comment by retlehs** [comment]
because with bedrock you already have cleaner URLs, as mentioned in the README

```
/app/themes/themename/
/app/plugins/
```

the current roots.io is also reallllllllllllly old at this point, it's running a prototype bedrock version that we worked on before releasing bedrock and also a pretty old version of the roots theme (before 7)

**Comment by intelligence** [comment]
Fair enough! I'm a neat freak so I'll tinker with this a bit see if I run into any issues. Might submit a PR if you're not planning on removing this all together.
