### ISSUE TITLE
Compatibility with Sage

### ISSUE THREAD

**Issue by kjprince** [roots/roots-rewrites#11]
Hey I can't seem to get the rewrites working on the new Sage theme. I've added the rewrites to my nginx configuration but no dice. Has this plugin been deprecated with the introduction of Sage?

**Comment by retlehs** [comment]
not supported, not recommended for a long time now, and won't be updated to support sage (but it wouldn't take much if you really want to do it)

**Comment by kjprince** [comment]
10-4.

Just curious—why is it not recommended?

**Comment by QWp6t** [comment]
Because we recommend using [roots/bedrock][1], which provides similar cosmetic value to this plugin.

[1]: /roots/bedrock
